// src/components/ExportReport.tsx ← 100% TYPE-SAFE
import React from 'react';
import { Download } from 'lucide-react';
import { useData } from '../context/DataContext';
import { saveAs } from 'file-saver';

const ExportReport: React.FC = () => {
  const { filteredSurgeries, filters, hasData } = useData();

  const generateReport = () => {
    if (!hasData || filteredSurgeries.length === 0) {
      alert('No data to export');
      return;
    }

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-GB').replace(/\//g, '-');
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });

    const totalCases = filteredSurgeries.length;
    const totalMinutes = filteredSurgeries.reduce((sum, s) => sum + s.duration, 0);
    const avgDuration = totalCases > 0 ? Math.round(totalMinutes / totalCases) : 0;

    const lastCase = [...filteredSurgeries].sort((a, b) => 
      new Date(`${b.date} ${b.time}`).getTime() - new Date(`${a.date} ${a.time}`).getTime()
    )[0];

    const uniqueSurgeons = new Set(filteredSurgeries.map(s => s.surgeon_name)).size;
    const uniqueProcedures = new Set(filteredSurgeries.map(s => s.procedure_name)).size;

    // Instrument stats with proper typing
    const instrumentMap = new Map<string, { duration: number; count: number }>();

    filteredSurgeries.forEach(surgery => {
      const names = (surgery.instruments_names || '')
        .split(',')
        .map((n: string) => n.trim())
        .filter(Boolean);

      const durations = (surgery.instruments_durations || '')
        .split(',')
        .map((d: string) => parseFloat(d) || 0);

      names.forEach((name: string, i: number) => {
        const dur = durations[i] || 0;
        if (name) {
          const existing = instrumentMap.get(name) || { duration: 0, count: 0 };
          instrumentMap.set(name, {
            duration: existing.duration + dur,
            count: existing.count + 1
          });
        }
      });
    });

    const instrumentLines = Array.from(instrumentMap.entries())
      .map(([name, stats]) => {
        const avg = stats.count > 0 ? Math.round(stats.duration / stats.count) : 0;
        const percent = totalMinutes > 0 ? Math.round((stats.duration / totalMinutes) * 100) : 0;
        return `${name}: ${avg} min (${percent}%)`;
      })
      .join('\n');

    const report = `MISSO SYSTEM INSIGHTS
Surgery Report

Date & Time: ${dateStr}, ${timeStr}
Procedure: ${filters.procedure || 'All Procedures'}
Surgeon: ${filters.surgeon || 'All Surgeons'}

QUICK STATISTICS
Total Cases: ${totalCases}
Average Duration: ${avgDuration} minutes
Total Console Time: ${totalMinutes} minutes
Unique Surgeons: ${uniqueSurgeons}
Unique Procedures: ${uniqueProcedures}

LAST CASE
Surgeon: ${lastCase?.surgeon_name || 'N/A'}
Procedure: ${lastCase?.procedure_name || 'N/A'}
Duration: ${lastCase?.duration || 0} minutes

INSTRUMENT USAGE
${instrumentLines || 'No instrument data'}

Generated by MISSO System Insights Dashboard`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `MISSO_Report_${dateStr}.txt`);

    const notif = document.createElement('div');
    notif.textContent = 'Report exported!';
    notif.className = 'fixed top-20 right-4 bg-[#00938e] text-white px-6 py-3 rounded-lg shadow-lg z-50 font-bold';
    document.body.appendChild(notif);
    setTimeout(() => notif.remove(), 3000);
  };

  return (
    <button
      onClick={generateReport}
      disabled={!hasData || filteredSurgeries.length === 0}
      className={`w-full flex items-center justify-center gap-2 p-3 border-2 border-[#00938e] rounded-lg font-medium transition-all ${
        hasData && filteredSurgeries.length > 0
          ? 'bg-white hover:bg-[#00938e] hover:text-white shadow-md'
          : 'bg-gray-200 text-gray-500 cursor-not-allowed'
      }`}
    >
      <Download size={20} />
      <span className="text-sm">Export Report</span>
    </button>
  );
};

export default ExportReport;